services:
  php-app:
    image: yiisoftware/yii2-php:8.3-apache
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '${APP_PORT}:80'
  # uncomment it if you don't have db
  # mysql-db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: 'stare_at_pdf'
  #   # ports:
  #     # - '3306:3306'
